import Hero from '../components/Hero';
import Header from '../components/Header';
import Head from 'next/head';
import Categories from '../components/Categories';
import Trusted from '../components/Trusted';
import Hire from '../components/Hire';
import Footer from '../components/Footer';
import Enterprise from '../components/Enterprise';
import Client from '@/components/Client';
import Upwork from '@/components/Upwork';
import Talent from '@/components/Talent';
import Support from '@/components/Support';
import Skils from '@/components/Skils';
import Testimonial from '@/components/Testimonial';

export default function Home() {
  return (
    <>
      <Head>
        <title>Upwork</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className='mx-auto md:px-[96px]'>
        <section className='px-[20px] md:px-[96px]'>
          <Hero />
          <Categories />
        </section>
        <section className='px-[20px] mt-[70px] md:px-[96px]'>
          <Trusted />
        </section>
        <section className='px-[20px] mb-[64px] md:px-[96px]'>
          <Hire />
        </section>
        <section className='md:px-[96px]'>
          <Enterprise />
        </section>
        <section className='mt-[50px] md:px-[96px]'>
          <Client />
        </section>
        <section className='mt-[30px] md:px-[96px]'>
          <Upwork />
        </section>
        <section className='mt-[30px] md:px-[96px]'>
          <Talent />
        </section>
        <section className='mt-[50px] px-[20px] md:px-[96px]'>
          <Testimonial />
        </section>
        <section className='mt-[30px] px-[20px] md:px-[96px]'>
          <Support />
        </section>
        <section className='pt-[60px] md:px-[96px]'>
          <Skils />
        </section>
      </div>
      <section className='px-10'>
          <Footer />
      </section>
    </>
  )
}
